spring:
  application:
    name: api-gateway

server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  service-url:
    defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    service-a:
      path: /service-a/**
      serviceId: service-a
      stripPrefix: false
    service-b:
          path: /service-b/**
          serviceId: service-b
          stripPrefix: false